# @name login
curl -X 'POST' \
  'http://127.0.0.1:3000/auth/login' \
  -H 'x-api-key: DUMMYIDEXAMPLE' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "siafin2010@gmail.com",
  "password": "123456A!"
}'

@accessToken = {{login.response.body.accessToken}}

###

# @name post-article

curl -X 'POST' \
  'http://127.0.0.1:3000/articles' \
  -H 'x-api-key: DUMMYIDEXAMPLE' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer {{accessToken}}' \
  -d '
{
  "content": "content4",
  "name": "name4",
  "sectionId": "2sSQ4pUbKUhKaaiuKjR8lzTUU0L",
  "status": "status4"
}'