curl -X 'POST' \
  'https://api.ukr.lublin.life/articles' \
  -H 'x-api-key: DUMMYIDEXAMPLE' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '
{
  "content": "content3",
  "name": "name3",
  "section": "section3",
  "status": "status3"
}'